In [24]:
# 데이터 생성
import pandas as pd

food = pd.DataFrame({
    "메뉴": ["김밥", "비빔밥", "자장면", "우동", "김밥", "자장면", "김밥"],
    "가격": [3000, 7000, 5500, 5500, 3500, 6000, 4000],
    "분류": ["한식", "한식", "중식", "일식", "한식", "중식", "한식"]
})
food

    메뉴    가격  분류
0   김밥  3000  한식
1  비빔밥  7000  한식
2  자장면  5500  중식
3   우동  5500  일식
4   김밥  3500  한식
5  자장면  6000  중식
6   김밥  4000  한식

In [25]:
food.info()
food.head() # 기본 5개 출력
food.tail(3)

# 통계 요약 
food.describe() #수치형(기본)
# food.describe(include='number')

food.describe(include='object') #문자형

# 고유한 값의 개수 - value_counts()
food["메뉴"].value_counts()
food["분류"].value_counts()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      int64
 2   분류      7 non-null      object
dtypes: int64(1), object(2)
memory usage: 300.0+ bytes

분류
한식    4
중식    2
일식    1
Name: count, dtype: int64

In [26]:
# 할인가 칼럼 추가 - 할인율 10%
discount = 0.1
food['할인가'] = food['가격'] * (1 - discount)
food

# 자료형 변환 - astype(자료형)
food['할인가'] = food['할인가'].astype('int64')
food

    메뉴    가격  분류   할인가
0   김밥  3000  한식  2700
1  비빔밥  7000  한식  6300
2  자장면  5500  중식  4950
3   우동  5500  일식  4950
4   김밥  3500  한식  3150
5  자장면  6000  중식  5400
6   김밥  4000  한식  3600

In [27]:
import pandas as pd 

# food 데이터를 csv 파일로 변환
food.to_csv("datas/food.csv", index=False)

# food 데이터 읽기
df = pd.read_csv("datas/food.csv")
df

    메뉴    가격  분류   할인가
0   김밥  3000  한식  2700
1  비빔밥  7000  한식  6300
2  자장면  5500  중식  4950
3   우동  5500  일식  4950
4   김밥  3500  한식  3150
5  자장면  6000  중식  5400
6   김밥  4000  한식  3600

In [30]:
# 정렬 - 오름차순, 내림차순 정렬 -> sort_values()
# df = df.sort_values("가격", ascending=True)
# inplace=True, 즉시 적용
# 가격을 오름차순 정렬
df.sort_values("가격", ascending=True, inplace=True)
df

# 가격을 높은 순으로 정렬 - 내림차순
df.sort_values("가격", ascending=False, inplace=True)
df

# 정렬 초기화 - sort_index()
df = df.sort_index()
df

    메뉴    가격  분류   할인가
0   김밥  3000  한식  2700
1  비빔밥  7000  한식  6300
2  자장면  5500  중식  4950
3   우동  5500  일식  4950
4   김밥  3500  한식  3150
5  자장면  6000  중식  5400
6   김밥  4000  한식  3600

In [41]:
# 조건 검색
# 메뉴가 '자장면'인 음식 정보
result1 = (df['메뉴'] == '자장면')
print(df[result1])
print('-----------------------------------')

# 가격이 4000원 미만인 음식 정보
result2 = (df['가격'] < 4000)
print(df[result2])
print('-----------------------------------')

# 메뉴가 '자장면' 이면서, 가격이 6000원 이상인 음식 정보
result3 = (df['메뉴'] == '자장면') & (df['가격'] >= 6000)
print(df[result3])
print('-----------------------------------')

# 메뉴가 '자장면' 이거나, 가격이 6000원 이상인 음식 정보
result4 = (df['메뉴'] == '자장면') | (df['가격'] >= 6000)
print(df[result4])
print('-----------------------------------')

# 분류가 '중식'이 아닌 음식을 검색하세요 
result5 = (df['분류'] != '중식')
print(df[result5])

    메뉴    가격  분류   할인가
2  자장면  5500  중식  4950
5  자장면  6000  중식  5400
-----------------------------------
   메뉴    가격  분류   할인가
0  김밥  3000  한식  2700
4  김밥  3500  한식  3150
-----------------------------------
    메뉴    가격  분류   할인가
5  자장면  6000  중식  5400
-----------------------------------
    메뉴    가격  분류   할인가
1  비빔밥  7000  한식  6300
2  자장면  5500  중식  4950
5  자장면  6000  중식  5400
-----------------------------------
    메뉴    가격  분류   할인가
0   김밥  3000  한식  2700
1  비빔밥  7000  한식  6300
3   우동  5500  일식  4950
4   김밥  3500  한식  3150
6   김밥  4000  한식  3600