In [1]:
import pandas as pd

# 데이터 생성
df = pd.DataFrame({
    "name": ['키보드', '마우스', 'USB 메모리'],
    "price": [20000, 32000, 11000]
})
df

# 칼럼 추가
df['spec'] = ['유선', '무선', '128GB']
df

# 칼럼명 변경 - rename() 함수 사용
df = df.rename(columns={
    "name": "품명",
    "price": "가격",
    "spec": "상세설명"
})
df

        품명     가격   상세설명
0      키보드  20000     유선
1      마우스  32000     무선
2  USB 메모리  11000  128GB

In [2]:
import pandas as pd

# csv 파일로 생성 - to_csv()
df.to_csv("computer.csv", index=False)

# csv 파일 읽기 - read_csv()
new_df = pd.read_csv("computer.csv")
new_df

df["품명"]
df["품명"][1]

'마우스'

### 행과 열 선택 
  1. loc[행이름, 열이름] - location을 의미
  2. iloc[행번호, 열번호] - integer location 의미

In [3]:
# 행 선택
print(df.loc[0:1])
print("-------------------------------")
print(df.iloc[0:1]) # 실제 출력(끝번호-1)
print("-------------------------------")

# 특정 요소
print(df.loc[0, "품명"])  #키보드
print(df.loc[1, "가격"])   #32000
print(df.loc[1:2, "상세설명"])
print("-------------------------------")
print(df.loc[1:2, ["품명", "상세설명"]])

    품명     가격 상세설명
0  키보드  20000   유선
1  마우스  32000   무선
-------------------------------
    품명     가격 상세설명
0  키보드  20000   유선
-------------------------------
키보드
32000
1       무선
2    128GB
Name: 상세설명, dtype: object
-------------------------------
        품명   상세설명
1      마우스     무선
2  USB 메모리  128GB

In [4]:
# print(df)
# 요소 변경하기
df.loc[0, "품명"] = "유선키보드"
print(df)

# 유선키보드의 가격을 25000으로 변경 - iloc 속성
df.iloc[0, 1] = 25000
print(df)

        품명     가격   상세설명
0    유선키보드  20000     유선
1      마우스  32000     무선
2  USB 메모리  11000  128GB
        품명     가격   상세설명
0    유선키보드  25000     유선
1      마우스  32000     무선
2  USB 메모리  11000  128GB

In [9]:
# 데이터 정보 - info()
df.info()

print(df)
# 행 데이터 추가
df.loc[3] = ["모니터", 120000, "22인치 LG 모니터"]
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   품명      3 non-null      object
 1   가격      3 non-null      int64
 2   상세설명    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes
        품명     가격   상세설명
0    유선키보드  25000     유선
1      마우스  32000     무선
2  USB 메모리  11000  128GB

        품명      가격         상세설명
0    유선키보드   25000           유선
1      마우스   32000           무선
2  USB 메모리   11000        128GB
3      모니터  120000  22인치 LG 모니터

### 행, 열 삭제
- 행 삭제: df.drop(행이름, axis=0)
- 열 삭제: df.drop(열이름, axis=1)

In [12]:
# 원본 유지 - copy()
df2 = df.copy()
df2

# 행 삭제 - 2행 삭제
df2 = df2.drop(2, axis=0)
df2

# 열 삭제 - 상세설명 칼럼
df2 = df2.drop("상세설명", axis=1)
df2

      품명      가격
0  유선키보드   25000
1    마우스   32000
3    모니터  120000